name: Run License Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  license_tests:
    uses: OpenVoiceOS/gh-automations/.github/workflows/license-check.yml@dev
    with:
      exclude_packages: '^(tqdm|bs4|gradio|bitstruct|attrs|referencing).*'
